---
title: "quantproj"
output: html_document
---

#LIBRARIES USEDh

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(lmtest)
library(pROC)
library(car)
library(datos)
```

##INITALISING

```{r init}

setwd("C:\\Users\\Roger\\Desktop\\R\\Data")
getwd()
veggiecc_data = read.csv("Survey_Results_count.csv")


veggiecc_data <- veggiecc_data %>%
      mutate(less_meat = ifelse(less_meat == "No",0,1))
veggiecc_data <- veggiecc_data %>%
      mutate(family_veg = ifelse(family_veg == "No",0,1))
veggiecc_data <- veggiecc_data %>%
      mutate(uni_student = ifelse(uni_student == "No",0,1))
veggiecc_data <- veggiecc_data %>%
      mutate(reduced_carbon_footprint = ifelse(reduced_carbon_footprint == "No",0,1))
veggiecc_data <- veggiecc_data %>%
      mutate(encouraged_others = ifelse(encouraged_others == "No",0,1))


#NEW BUCKETS FOR VARIABLE AGE AND REASON 

for (i in seq_along(veggiecc_data$Age)) {
  if(veggiecc_data$Age[i]=="<20" | veggiecc_data$Age[i]=="21-25" | veggiecc_data$Age[i]=="26-30") {veggiecc_data$Age[i]=1}
  else if(veggiecc_data$Age[i]=="45+") {veggiecc_data$Age[i]=3}
  else {veggiecc_data$Age[i]=2}
}

for (i in seq_along(veggiecc_data$reason_no_meat)) {
  if(veggiecc_data$reason_no_meat[i]=="Environmental/Climate Change") {veggiecc_data$reason_no_meat[i]=1}
  else if(veggiecc_data$reason_no_meat[i]=="Not applicable") {veggiecc_data$reason_no_meat[i]=NA}
  else if (veggiecc_data$reason_no_meat[i]=="") {veggiecc_data$reason_no_meat[i]=NA}
  else {veggiecc_data$reason_no_meat[i]=0}
}


IsVegetarian = veggiecc_data$IsVegetarian
StudiesClimateChange = veggiecc_data$climate_change_course2
less_meat = veggiecc_data$less_meat
gender = veggiecc_data$Gender
family_veg = veggiecc_data$family_veg
age = as.numeric(veggiecc_data$Age)
nationality = veggiecc_data$Nationality
uni_student = veggiecc_data$uni_student
ReducedCarbonFootprint = veggiecc_data$reduced_carbon_footprint
meat_freq = veggiecc_data$meat_frequency2
reason = as.numeric(veggiecc_data$reason_no_meat)
encouraged_others = veggiecc_data$encouraged_others

```
#DATA

```{r summarydata}

veggiecc_data %>% group_by(Age) %>% summarise(n())
veggiecc_data %>% group_by(Nationality) %>% summarise(n())
veggiecc_data %>% group_by(family_veg) %>% summarise(n())
veggiecc_data %>% group_by(less_meat) %>% summarise(n())
veggiecc_data %>% group_by(encouraged_others) %>% summarise(n())

```



#REGRESSIONS OF OUR CATEGORICAL NON-BINARY VARIABLES

```{r regrtry1}

#Trying age

model_0log = glm(IsVegetarian ~ age, data = veggiecc_data, family = binomial(logit))
summary(model_0log)

model_00log = glm(IsVegetarian ~ 0 + age, data = veggiecc_data, family = binomial(logit))
summary(model_00log)

```

```{r regrtry2}

#Trying our non binary variables

model_000log = glm(IsVegetarian ~ nationality, data = veggiecc_data, family = binomial(logit))
summary(model_000log)

model_0000log = glm(IsVegetarian ~ 0+ nationality, data = veggiecc_data, family = binomial(logit))
summary(model_0000log)

```

#REGRESSIONS HISTORY. Here can see a little bit the timeline of our project. We began wanting to explain which is the relation between IsVegetarian ~ StudiesClimateChange.

```{r regr1log}

#This logistic regression permits to calculate the probability of being vegan if you are studying climate change

model_1log = glm(IsVegetarian ~ StudiesClimateChange, data = veggiecc_data, family = binomial(logit))
summary(model_1log)


#Plots to validate the residuals and all the requisites of a good regression
plot(model_1log)

```

```{r regr1lm}

#Here we try to work a linear probability model to see if the results are similar and we can use this model.

model_1lm = lm(IsVegetarian ~ StudiesClimateChange, data = veggiecc_data)
summary(model_1lm)


#Plots to validate the residuals and all the requisites of a good regression
plot(model_1lm)

```

```{r regr1plot}


plot(x = StudiesClimateChange, 
     y = IsVegetarian,
     main = "Probit and Logit Models Model of the Probability of Denial, Given P/I Ratio",
     xlab = "Studies Climate Change?",
     ylab = "Is Vegan?",
     pch = 20,
     ylim = c(-0.4, 1.4),
     cex.main = 0.9)
abline(h = 1, lty = 2, col = "darkred")
abline(h = 0, lty = 2, col = "darkred")
text(0.8, 0.9, cex = 0.8, "Is Vegetarian")
text(0.8, -0.1, cex= 0.8, "Not Vegetarian")
x <- seq(0, 3, 0.01)
y_lm <- predict(model_1lm, list(StudiesClimateChange = x), type = "response")
y_logit <- predict(model_1log, list(StudiesClimateChange = x), type = "response")
lines(x, y_lm, lwd = 1.5, col = "steelblue")
lines(x, y_logit, lwd = 1.5, col = "black", lty = 2)
legend("topleft",
       horiz = TRUE,
       legend = c("Linear", "Logit"),
       col = c("steelblue", "black"), 
       lty = c(1, 2))


```


```{r regr1lmlog}

#We conduct a linear hypothesis test to see if the StudiesClimateChange is the same for the two models.
anova(model_1log, test ='Chisq')

```



```{r regr1GOF}

#Goodness of fits. We see that our model with the predictor StudiesClimateChange is significant compared to the NULL model.

anova(model_1log, test ='Chisq')

```


```{r regr1ROC}

#Plotting the ROC curve for assessing discriminating power of our model

predpr <- predict(model_1log,type=c("response"))
roccurve <- roc(IsVegetarian ~ predpr)
auc(roccurve)
plot(roccurve)

```


```{r regr2}

#Logistic regression with everything inside. To see if there is anything else we hadn't think of at first that is statistically significant

model_2log = glm(IsVegetarian ~ StudiesClimateChange + reason + age + encouraged_others + family_veg + gender + uni_student + ReducedCarbonFootprint + nationality, data = veggiecc_data, family = binomial(logit))
summary(model_0log)

#Plots to validate the residuals and all the requisites of a good regression
plot(model_2log)

```


```{r regr3}

#Same logistic regression only with the two statistically significant variables. ANOVA to test if this model improves the predicting capacity of the null model

model_3log = glm(IsVegetarian ~ StudiesClimateChange + uni_student, data = veggiecc_data, family = binomial(logit))
summary(model_2log)

plot(model_3log)
anova(model_3log, test ='Chisq')

```




```{r testcorr1}

#HERE WE SEE THAT THESE ARE STRONGLY CORRELATED REGRESSORS.THIS IS LOGIC, BECAUSE ALMOST ALL THE "YES" OF StudiesClimateChange are a "YES" in uni_student. THEREFORE, WE SHOULD EXCLUDE THIS VARIABLE FROM OUR MODEL.

mytable <- table(StudiesClimateChange, uni_student)
print(mytable)
chi2=chisq.test(mytable, correct=FALSE)
print(chi2)
phi=sqrt(chi2$statistic / sum(mytable))
print(phi)

```


```{r testcorr2}

lrtest(model_2log, model_1log)

#Compare the model with all the variables to a null one (only Beta-zero)

lrtest(model_2log)

```

```{r regr4}

#This is our final model in logit. Including reason and age to avoid reverse causality (exogeneity)

model_4log = glm(IsVegetarian ~ StudiesClimateChange + reason + age, data = veggiecc_data, family = binomial(logit))
summary(model_4log)


#Plots to validate the residuals and all the requisites of a good regression
plot(model_4log)

```
```{r regr5}

#This is our final model in lm. Including reason and age to avoid reverse causality (exogeneity)

model_5lm = lm(IsVegetarian ~ StudiesClimateChange + reason + age, data = veggiecc_data)
summary(model_5lm)

#Plots to validate the residuals and all the requisites of a good regression
plot(model_5lm)

```


#REGRESSING OTHER THINGS

```{r regr3lm}

#This linear regression will try to see which variables affect the rate of consumption of meet per week. Also we test if there is multicolinearity 

model_3 = lm(meat_freq ~ StudiesClimateChange + gender + ReducedCarbonFootprint  , data = veggiecc_data)
summary(model_3)
vif(model_3)

```